[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
enableStaticServing = true
port = 8501

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"